const std = @import("std");

// Usage: asset-hash <manifest.zig> <public-dir> <stem>.<ext> ...
//
// For each input filename (expected to already exist in <public-dir>):
//   1. SHA-256 the contents, take the first 8 bytes as a 16-hex fingerprint.
//   2. Delete any stale `<stem>.<oldhash>.<ext>` left by a previous build.
//   3. Rename `<stem>.<ext>` → `<stem>.<hash>.<ext>`.
//
// Emits <manifest.zig> with one `pub const <stem>_<ext> = "/<hashed>";`
// per input, so the server can @import it as a module.

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const a = gpa.allocator();

    const args = try std.process.argsAlloc(a);
    defer std.process.argsFree(a, args);

    if (args.len < 3) {
        std.debug.print("Usage: asset-hash <manifest.zig> <public-dir> <stem>.<ext>...\n", .{});
        return;
    }

    const manifest_path = args[1];
    const public_dir = args[2];

    var manifest: std.ArrayList(u8) = .empty;
    defer manifest.deinit(a);
    const w = manifest.writer(a);

    try w.writeAll("// Auto-generated by asset-hash; do not edit.\n\n");

    for (args[3..]) |file| {
        const dot = std.mem.lastIndexOfScalar(u8, file, '.') orelse return error.NoExtension;
        const stem = file[0..dot];
        const ext = file[dot + 1 ..];

        const src_path = try std.fs.path.join(a, &.{ public_dir, file });
        defer a.free(src_path);

        const bytes = try std.fs.cwd().readFileAlloc(a, src_path, 50 * 1024 * 1024);
        defer a.free(bytes);

        var digest: [32]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
        const full_hex = std.fmt.bytesToHex(digest, .lower);
        const hash = full_hex[0..16];

        const hashed_name = try std.fmt.allocPrint(a, "{s}.{s}.{s}", .{ stem, hash, ext });
        defer a.free(hashed_name);

        try cleanStale(a, public_dir, stem, ext, file, hashed_name);

        const dst_path = try std.fs.path.join(a, &.{ public_dir, hashed_name });
        defer a.free(dst_path);
        try std.fs.cwd().rename(src_path, dst_path);

        try w.print("pub const {s}_{s} = \"/{s}\";\n", .{ stem, ext, hashed_name });

        const src_disp = try std.fs.path.join(a, &.{ public_dir, file });
        defer a.free(src_disp);
        const dst_disp = try std.fs.path.join(a, &.{ public_dir, hashed_name });
        defer a.free(dst_disp);

        appendStats(a, "HASH", src_disp, dst_disp, bytes.len, bytes.len) catch {
            std.debug.print(
                "\x1b[45;97m HASH \x1b[0m  {s} \x1b[2m→\x1b[0m {s}\n",
                .{ file, hashed_name },
            );
        };
    }

    if (std.fs.path.dirname(manifest_path)) |d| std.fs.cwd().makePath(d) catch {};
    try std.fs.cwd().writeFile(.{ .sub_path = manifest_path, .data = manifest.items });
}

fn appendStats(
    a: std.mem.Allocator,
    kind: []const u8,
    src: []const u8,
    dst: []const u8,
    n_in: u64,
    n_out: u64,
) !void {
    const log_path = std.process.getEnvVarOwned(a, "BUNDLE_STATS_LOG") catch return error.NoStatsLog;
    defer a.free(log_path);
    var file = try std.fs.cwd().createFile(log_path, .{ .truncate = false });
    defer file.close();
    try file.seekFromEnd(0);
    var buf: [512]u8 = undefined;
    const line = try std.fmt.bufPrint(&buf, "{s}|{s}|{s}|{d}|{d}\n", .{ kind, src, dst, n_in, n_out });
    try file.writeAll(line);
}

// Removes stale `<stem>.*.<ext>` siblings so only the freshly-hashed
// file remains after the rename.
fn cleanStale(
    a: std.mem.Allocator,
    public_dir: []const u8,
    stem: []const u8,
    ext: []const u8,
    src_basename: []const u8,
    dst_basename: []const u8,
) !void {
    var dir = std.fs.cwd().openDir(public_dir, .{ .iterate = true }) catch return;
    defer dir.close();
    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.startsWith(u8, entry.name, stem)) continue;
        if (!std.mem.endsWith(u8, entry.name, ext)) continue;
        if (std.mem.eql(u8, entry.name, src_basename)) continue;
        if (std.mem.eql(u8, entry.name, dst_basename)) continue;
        // Make sure it matches `<stem>.<something>.<ext>` shape.
        const afterStem = entry.name[stem.len..];
        if (afterStem.len == 0 or afterStem[0] != '.') continue;
        const path = try std.fs.path.join(a, &.{ public_dir, entry.name });
        defer a.free(path);
        std.fs.cwd().deleteFile(path) catch {};
    }
}
